package ec.com.sisapus.modelo;
// Generated 11/01/2015 05:37:11 PM by Hibernate Tools 3.2.1.GA



/**
 * DetallePresupuesto generated by hbm2java
 */
public class DetallePresupuesto  implements java.io.Serializable {


     private Integer codigoDetPres;
     private CabeceraPresupuesto cabeceraPresupuesto;
     private Analisispreciounitario analisispreciounitario;
     private String nombreDetPres;
     private String unidadDetPres;
     private String categoriaDetPres;
     private Integer cantidadDetPres;
     private Double punitDetPres;
     private Double ptotDetPres;

    public DetallePresupuesto() {
        this.codigoDetPres = 0;
        this.cabeceraPresupuesto = new CabeceraPresupuesto();
        this.analisispreciounitario = new Analisispreciounitario();
    }

    public DetallePresupuesto(CabeceraPresupuesto cabeceraPresupuesto, Analisispreciounitario analisispreciounitario, String nombreDetPres, String unidadDetPres, String categoriaDetPres, Integer cantidadDetPres, Double punitDetPres, Double ptotDetPres) {
       this.cabeceraPresupuesto = cabeceraPresupuesto;
       this.analisispreciounitario = analisispreciounitario;
       this.nombreDetPres = nombreDetPres;
       this.unidadDetPres = unidadDetPres;
       this.categoriaDetPres = categoriaDetPres;
       this.cantidadDetPres = cantidadDetPres;
       this.punitDetPres = punitDetPres;
       this.ptotDetPres = ptotDetPres;
    }
   
    public Integer getCodigoDetPres() {
        return this.codigoDetPres;
    }
    
    public void setCodigoDetPres(Integer codigoDetPres) {
        this.codigoDetPres = codigoDetPres;
    }
    public CabeceraPresupuesto getCabeceraPresupuesto() {
        return this.cabeceraPresupuesto;
    }
    
    public void setCabeceraPresupuesto(CabeceraPresupuesto cabeceraPresupuesto) {
        this.cabeceraPresupuesto = cabeceraPresupuesto;
    }
    public Analisispreciounitario getAnalisispreciounitario() {
        return this.analisispreciounitario;
    }
    
    public void setAnalisispreciounitario(Analisispreciounitario analisispreciounitario) {
        this.analisispreciounitario = analisispreciounitario;
    }
    public String getNombreDetPres() {
        return this.nombreDetPres;
    }
    
    public void setNombreDetPres(String nombreDetPres) {
        this.nombreDetPres = nombreDetPres;
    }
    public String getUnidadDetPres() {
        return this.unidadDetPres;
    }
    
    public void setUnidadDetPres(String unidadDetPres) {
        this.unidadDetPres = unidadDetPres;
    }
    public String getCategoriaDetPres() {
        return this.categoriaDetPres;
    }
    
    public void setCategoriaDetPres(String categoriaDetPres) {
        this.categoriaDetPres = categoriaDetPres;
    }
    public Integer getCantidadDetPres() {
        return this.cantidadDetPres;
    }
    
    public void setCantidadDetPres(Integer cantidadDetPres) {
        this.cantidadDetPres = cantidadDetPres;
    }
    public Double getPunitDetPres() {
        return this.punitDetPres;
    }
    
    public void setPunitDetPres(Double punitDetPres) {
        this.punitDetPres = punitDetPres;
    }
    public Double getPtotDetPres() {
        return this.ptotDetPres;
    }
    
    public void setPtotDetPres(Double ptotDetPres) {
        this.ptotDetPres = ptotDetPres;
    }




}


